### ISSUE TITLE
Causes regression from Symfony2.3

### ISSUE THREAD

**Issue by mitom** [schmittjoh/JMSSecurityExtraBundle#146]
The bundle overwrites the configuration from Symfony2.3 and removes the ability to use the 'ips' key in access_controls as described in the [docs](http://symfony.com/doc/current/book/security.html#securing-by-ip)

**Comment by ip512** [comment]
Correct me if I'm wrong, but this fix does not seems to be in latest version (1.5.1) : 
https://github.com/schmittjoh/JMSSecurityExtraBundle/blob/1.5.1/DependencyInjection/AccessControlConfiguration.php
Is it possible to include it in the latest stable release ?
