### ISSUE TITLE
Does bundle work with Symfony 2.4.3

### ISSUE THREAD

**Issue by kvaje** [schmittjoh/JMSSecurityExtraBundle#173]
Hi,

does this bundle work with Symfony 2.4.3?
I have installed it, but it is not working, so I don't know if the problem is on my side or on bundle side.
JMSSecurityExtraBundle: 1.5.1
jms/di-extra-bundle: 1.3

**Comment by Ener-Getick** [comment]
Without more information we can't help you.
The bundle should be compatible with sf 2.4 (it is with 2.3) but it is still possible that symfony 2.4 contains bugs that aren't fixed (it not supported anymore).
