### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by KamilKopaczyk** [schmittjoh/JMSSecurityExtraBundle#180]
Can we expect new, stable release soon?

Current 1.5.1 was tagged a year ago and it collides with Symfony security component (for example: 'ips' under access control)

**Comment by notrix** [comment]
:+1:

**Comment by ulas-atila** [comment]
:+1:

**Comment by giovkanata** [comment]
:+1:

**Comment by luishdez** [comment]
:+1:

**Comment by ip512** [comment]
:+1:

**Comment by Matthimatiker** [comment]
:+1:

**Comment by Ener-Getick** [comment]
[``1.5.2``](https://github.com/schmittjoh/JMSSecurityExtraBundle/releases/tag/1.5.2) was released in december 2015.
