### ISSUE TITLE
Expressions > How to check if an integer matches a specific value?

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSSecurityExtraBundle#182]
It's forbidden to write an expression like `user.getId() == 1` because that throws an exception:
```
Expected primary expression, but got "2" of type T_NONE at position 41 (0-based).
```

So I have to write `user.getId() == "1"` which always fails because by default, IsEqualExpressionCompiler, does a strict `===` comparison. 

Why does `==` evaluates to `===`? Wouldn't it be better to just add an extra `===` expression as well?

**Comment by stof** [comment]
changing the existing operator now is not an option. It would be a BC break.

However, not supporting numbers is really weird.

**Comment by schmittjoh** [comment]
Yeah, we should support integers at least.

**Comment by ruudk** [comment]
Is it simple to fix? I can look into to it but don't feel like refactoring the whole thing ;)

**Comment by schmittjoh** [comment]
Should be easy (in particular integer support only). Just add another lexer token, and make the parser aware of it.

**Comment by stof** [comment]
Supporting it is a matter of updating 2 places:

- the [ExpressionLexer](https://github.com/schmittjoh/JMSSecurityExtraBundle/blob/master/Security/Authorization/Expression/ExpressionLexer.php) to add a new token type, add a matching group in the regex to match integers and then detect the new token type in the dedicated method
- the [ExpressionParser](https://github.com/schmittjoh/JMSSecurityExtraBundle/blob/master/Security/Authorization/Expression/ExpressionParser.php) to build a ConstantExpression for this new token

**Comment by ruudk** [comment]
Thanks :) It works, see #183
