### ISSUE TITLE
Compatibility with PHP7

### ISSUE THREAD

**Issue by DocLommi** [schmittjoh/JMSSecurityExtraBundle#191]
Seems as if the String class breaks PHP7 compatibility. Is there an option to just rename it ? Like UtilString or something ?

**Comment by stof** [comment]
a better solution would be to deprecate it entirely and use ``hash_equals`` (and the hash_equals polyfill)

**Comment by DocLommi** [comment]
agree. like seen with the Bool classes in the ruflin/Elastica lib. Thnx for quick response ^^

**Comment by DocLommi** [comment]
Agree.

**Comment by stof** [comment]
As long as the deprecated code is not triggered, this is fine, as the class will not be loaded

**Comment by ruudk** [comment]
@DocLommi Are you working on a PR? :)

**Comment by Jean85** [comment]
I'm reviewing the code to make a PR, but I don't see any usage of this class inside this project.

I think that what @stof proposed is the best course of action, but we should also make some choiches about composer.json. I would like to do this in my PR:

 * mark PHP ~5.3, so remark PHP 7 as incompatible right now with 1.x versions
 * deprecate the `String` class
 * plan a major version bump (2.0) where PHP7 is supported, and `String` class removed

I'll work on the PR right now...

**Comment by Jean85** [comment]
Ok, the PR is merged now, we should remove the class in a next major and add 7.0 in the travis matrix..

**Comment by Jean85** [comment]
We have also #202 ready to be merged and that fixes this issue!

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/202
