### ISSUE TITLE
Make it compatible with Symfony 3.0

### ISSUE THREAD

**Issue by francoispluchino** [schmittjoh/JMSSecurityExtraBundle#194]
Is it planned to make it compatible this Bundle with Symfony 3.0?

**Comment by kniziol** [comment]
That's good and important question
Is there any info when it could be?

**Comment by Wirone** [comment]
Same question here. I got deprecation warnings from this bundle.

**Comment by pinouf** [comment]
+1

**Comment by JoydS** [comment]
+1

**Comment by schmittjoh** [comment]
Please provide a pull-request if you need Symfony3 support before I get to it.

**Comment by maurotrentini** [comment]
+1

**Comment by sblondeau** [comment]
@schmittjoh I think the [pull-request](https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/202) is ready since a while. Thx in advance to merge it !
Have a nice week-end

**Comment by Ener-Getick** [comment]
https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/202 merged ! 
Please test ``dev-master`` on your projects and tell me if you have any errors :-)

**Comment by boast** [comment]
Thank you for your efforts @Ener-Getick !!

Sadly, https://github.com/schmittjoh/JMSDiExtraBundle is not ready for Symfony 3.0 (I recall a patch / PR should be available, though). The JMSDiExtraBundle also restricts the JMSAopBundle to version 1.1, whereas 1.2 would be available and is 3.0 ready.

**Comment by Ener-Getick** [comment]
Yeah this is in progress too ☺

**Comment by boast** [comment]
:-) nice, I was just yesterday thinking "bummer, that probably takes a while to migrate all of those repos, lets go back to 2.8". 3.0? Here I come!

**Comment by francoispluchino** [comment]
@Ener-Getick `jms/di-extra-bundle`:`1.6.0` (or `dev-master`) required Symfony `~2.1`, not `~2.3|~3.0`.

It's therefore impossible to install this bundle with Symfony 3 for the moment.

Waiting to merge schmittjoh/JMSDiExtraBundle#227.

**Comment by Ener-Getick** [comment]
@francoispluchino see https://github.com/schmittjoh/JMSDiExtraBundle/pull/227 ;-)

**Comment by francoispluchino** [comment]
@Ener-Getick Yes, but this PR is not merged for the moment :). Strange that the tests successfully pass with Symfony 3, while a dependency require Symfony 2 (besides, the tests do not pass on Travis in the section 'allowed failures').

It would have been better to wait the merge of the PR of JMSDiExtraBundle before release a beta version of this bundle?

**Comment by Ener-Getick** [comment]
@francoispluchino The problem is that JMSDiExtraBundle depends on JMSSecurityExtraBundle too so if I didn't release one of them, we would be locked...

**Comment by francoispluchino** [comment]
@Ener-Getick Indeed, I hadn't seen that it was required for the `dev`. In this case I understand :-).

Thank you for your efforts!

**Comment by Ener-Getick** [comment]
@francoispluchino I merged https://github.com/schmittjoh/JMSDiExtraBundle/pull/227 ;-)

**Comment by francoispluchino** [comment]
@Ener-Getick Thank you !!!

**Comment by Ener-Getick** [comment]
@francoispluchino I will see if there are PRs waiting to be merged before creating an RC phase.
