### ISSUE TITLE
Impossible to install the last release 1.5.2 on php 7.0.0

### ISSUE THREAD

**Issue by A-contresens** [schmittjoh/JMSSecurityExtraBundle#196]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jms/security-extra-bundle dev-master requires php ~5.3 -> your PHP version (7.0.0) or "config.platform.php" value does not satisfy that requirement.
    - jms/security-extra-bundle dev-master requires php ~5.3 -> your PHP version (7.0.0) or "config.platform.php" value does not satisfy that requirement.
    - Installation request for jms/security-extra-bundle dev-master -> satisfiable by jms/security-extra-bundle[dev-master].

**Comment by AlexandreHagen** [comment]
Same problem to me

**Comment by NodokaMurmevent** [comment]
same problem

 ``  - jms/security-extra-bundle dev-master requires php ~5.3 -> your PHP version (7.0.1-1~dotdeb+8.1) or value of "config.platform.php" in composer.json does not satisfy that requirement.``
    ``- jms/security-extra-bundle dev-master requires php ~5.3 -> your PHP version (7.0.1-1~dotdeb+8.1) or value of "config.platform.php" in composer.json does not satisfy that requirement.``
   `` - Installation request for jms/security-extra-bundle dev-master -> satisfiable by jms/security-extra-bundle[dev-master].``

**Comment by thomask** [comment]
+1

**Comment by thomask** [comment]
Created a pull request #200

**Comment by Jean85** [comment]
This will be fixed by #202

**Comment by francoispluchino** [comment]
Duplicate with #191.

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/202
