### ISSUE TITLE
Call to undefined method JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager::setVoters()

### ISSUE THREAD

**Issue by kherge** [schmittjoh/JMSSecurityExtraBundle#201]
In a `dev` environment, if I do a clean install (no cache), I get the following error message:

    PHP Fatal error:  Call to undefined method JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager::setVoters() in /home/kherrera/Workspace/Open Source/Crest/app/cache/dev/appDevDebugProjectContainer.php on line 2893

I trigger it by running `app/console`, and it does not appear again once the cache files have been generated.

**Comment by kherge** [comment]
This block of code in `appDevDebugProjectContainer.php` is causing the error:

```php
    /**
     * Gets the 'security.access.decision_manager' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager A JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager instance.
     */
    protected function getSecurity_Access_DecisionManagerService()
    {
        $a = $this->get('security.authentication.trust_resolver');

        $b = new \JMS\SecurityExtraBundle\Security\Authorization\Expression\LazyLoadingExpressionVoter($this->get('security.expressions.handler'), $this->get('monolog.logger.security', ContainerInterface::NULL_ON_INVALID_REFERENCE));
        $b->setLazyCompiler($this, 'security.expressions.compiler');
        $b->setCacheDir((__DIR__.'/jms_security/expressions'));

        $this->services['security.access.decision_manager'] = $instance = new \JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager(new \Symfony\Component\Security\Core\Authorization\AccessDecisionManager(array(), 'affirmative', false, true));

        $instance->setVoters(array(0 => $b, 1 => new \Symfony\Component\Security\Core\Authorization\Voter\RoleVoter(), 2 => new \Symfony\Component\Security\Core\Authorization\Voter\ExpressionVoter(new \Symfony\Component\Security\Core\Authorization\ExpressionLanguage(), $a, $this->get('security.role_hierarchy', ContainerInterface::NULL_ON_INVALID_REFERENCE)), 3 => new \Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter($a)));

        return $instance;
    }
```

I'm looking through the bundle's configuration files and extension classes but I don't see (or can't tell) what is causing it. I wonder if this has something to do with my using Symfony 2.8.1.

**Comment by kherge** [comment]
Okay, I figured it out.

1. This issue is specific to a security feature added to Symfony in the 2.8 release ([#14733](https://github.com/symfony/symfony/pull/14733)).
2. The JMS `RememberingAccessDecisionManager` replaces the default class used for the `security.access.decision_manager` service.
3. The Symfony Security bundle assumes that the class used for the service has the `setVoters` method.

Now here's the question:

- Is this Symfony's problem because it assumes that `setVoters` is available?
- Or is this an issue with the JMS Security Extra bundle providing an incompatible decision manager?

If the former, I can open a ticket with Symfony and get the ball rolling on fixing it on their end. If the latter, I can create a patch.

**Comment by kasparsklavins** [comment]
Any progress on this?

**Comment by Ener-Getick** [comment]
@kherge for me that's an issue in JMSSecurityExtraBundle and should be fixed by executing the ``IntegrationPass`` later.

**Comment by schmittjoh** [comment]
It may be easier to just add the method and delegate it.

**Comment by stof** [comment]
The issue is that the bundle replaces the class of a service it does not own, and its replacement class is not compatible with the original one. There is no bug in Symfony there, as this is not something for which Symfony provides BC (which is why we stopped defining classes as parameters btw)

**Comment by TheCelavi** [comment]
Temporary fix proposed: https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/208

Proper fix would be to modify JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager which should inherit SF's original ADM, however, only benefit is in dev mode, where RememberingAccessDecisionManager is not essential.
