### ISSUE TITLE
SF3: voters mismatch/misconfigured?

### ISSUE THREAD

**Issue by ErikTrapman** [schmittjoh/JMSSecurityExtraBundle#213]
In trying to upgrade a repository from SF2.8 to SF3 I encoutered some problems with the login. Firstly I assumed it was a problem inside my project, but to test further I've created a clean SF3 project with only Fos-Userbundle installed. When I try the login all works fine. But in the project I want to upgrade I also use the SecurityExtraBundle to perform authentication checks with annotations. So in my new clean project I enable the SecurityExtraBundle, and then I have the following problems:
- I cannot reach the login page anymore because I get stuck in an infinite loop
- When I disable the SEB I can login, and when I enable the SEB again while still logged in I get a Exception about missing voters when trying to access the profiler-page regarding login:
  ![image](https://cloud.githubusercontent.com/assets/1147578/18027590/5a42511e-6c68-11e6-9724-df032e6745bf.png)

I've created this project here https://github.com/ErikTrapman/jmstest so anybody can try to reproduce the same things.

Do I need to configure something in the SecurityExtraBundle I'm missing?

**Comment by wendel841** [comment]
+1 for this issues, any ideas? symfony 3.1 standart + plain installation of bundle

**Comment by GuilhemN** [comment]
This should be fixed in 1.6.1.
