### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by jaymecd** [schmittjoh/JMSSecurityExtraBundle#214]
@schmittjoh, any plans for next release?
9 important commits to master since last release (1.6.0)

**Comment by dovys** [comment]
+1

**Comment by aaleksandrov** [comment]
+1

**Comment by bobvandevijver** [comment]
It has been a few months already, and I've spend a lot of time debugging today on the missing voters which are fixed in #209. 

For now working on `dev-master` works, but a release would be nice :+:

**Comment by Ener-Getick** [comment]
I released [1.6.1](https://github.com/schmittjoh/JMSSecurityExtraBundle/releases/tag/1.6.1), sorry for the delay.
